### ISSUE TITLE
How to use Inter-blockchain communication with Ethereum?

### ISSUE THREAD

**Issue by webmaster128** [vocdoni/docs#2]
The docs suggest that a Tendermint-based Vochain and Ethereum mainnet can use [IBC](https://cosmos.network/ibc/) to communicate:

> We can also use interchain communication in order to pass messages between blockchains and trigger certain actions.

However, this is a non-trivial task – if at all possible – for blockchains with probabilistic finality like Ethereum 1.x. https://cosmos.network/intro#probabilistic-finality-chains described how this can work for moving tokens around using escrow contracts. The given example implies a messaging delay of 20 minutes and has a very limited use case.

If this is still the way to go, I think we need to document more about how this communication could potentially look like.

**Comment by jordipainan** [comment]
Hi! By inter-chain communication we are not referring explicitly to [IBC](https://cosmos.network/ibc/).

Our current approach is to use Oracles. Each Oracle can read events triggered by Ethereum smart contracts and can create  "special" transactions that will be sended to the Vochain.
Only transactions sent by the Oracles registered into the Vochain (identified by public keys) will be valid.
