### ISSUE TITLE
Mention of (pk.X, pk.Y) in zk-census-proof.md

### ISSUE THREAD

**Issue by ed255** [vocdoni/docs#49]
In https://github.com/vocdoni/docs/blob/master/src/architecture/protocol/anonymous-voting/zk-census-proof.md
The current proposal doesn't use an elliptic curve for public key, but there are mentions of pk.X and pk.Y:
> the public key of the private key is inside a Hash, which is inside the Merkle Tree with the CensusRoot (key=Poseidon(pk.X, pk.Y), value=0)

https://raw.githubusercontent.com/vocdoni/docs/master/src/architecture/protocol/anonymous-voting/zk-census-proof-poseidon-merkletree-diagram.png

**Comment by arnaucube** [comment]
Yes, this is being fixed in this PR: https://github.com/vocdoni/docs/pull/47

**Comment by arnaucube** [comment]
Closing this issue as this has been fixed in #47 & #50
