### ISSUE TITLE
The "Last Update" note in each page has an unexpected date

### ISSUE THREAD

**Issue by ed255** [vocdoni/docs#63]
At the end of each rendered page there's a note like this:
```
Last Updated: 8/5/2021, 8:36:13 AM
``` 
I was expecting this value to be the last time that particular page was updated, but that's not the case; as I'm seeing pages that haven't been updated in the previous week, yet the "Last Update" for those pages is today.

Maybe what's currently showing is the last time the entire docs was built?  If that's the case, I think showing this value in each page can be confusing.

**Comment by NateWilliams2** [comment]
Ah, good catch. I'll see if this plugin has an option to just display on the home page, or to display an accurate value for each page. Otherwise I'll disable it.

**Comment by NateWilliams2** [comment]
When I host locally, each page has its own accurate timestamp. So I'm guessing the problem is that the deployment action on github builds an entirely new site, making the plugin think every page is new. Looking into this..
